version: '3'

services:
  httpd:
    container_name: httpd
    restart: unless-stopped
    image: httpd:latest
    volumes:
      - ./html:/usr/local/apache2/htdocs
    ports:
      - "80:80"
networks:
  default:
    external:
      name:
        web_network_lemp